<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="DataClassesTestDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BOTULY-PC\SQLEXPRESS;Initial Catalog=TestDB;Persist Security Info=True;User ID=SqlTestUser" SettingsObjectName="LinqTest.Properties.Settings" SettingsPropertyName="TestDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="taskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="startTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="endTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="occurences" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="period" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="Task_TaskReceiver" Member="TaskReceivers" ThisKey="taskID" OtherKey="taskID" Type="TaskReceiver" />
      <Association Name="User_Task" Member="User" ThisKey="userID" OtherKey="userID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="contactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Contact" Member="User" ThisKey="userID" OtherKey="userID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaskReceivers" Member="TaskReceivers">
    <Type Name="TaskReceiver">
      <Column Name="receiverID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Task_TaskReceiver" Member="Task" ThisKey="taskID" OtherKey="taskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="JID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Task" Member="Tasks" ThisKey="userID" OtherKey="userID" Type="Task" />
      <Association Name="User_Contact" Member="Contacts" ThisKey="userID" OtherKey="userID" Type="Contact" />
    </Type>
  </Table>
</Database>