<?xml version="1.0" encoding="utf-8"?><Database Name="ReminderDB" Class="ReminderDBClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BOTULY-PC\SQLEXPRESS;Initial Catalog=ReminderDB;Persist Security Info=True;User ID=SqlTestUser;Pooling=False" SettingsObjectName="GTalk_Reminder_Bot.Properties.Settings" SettingsPropertyName="ReminderDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="taskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="startTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="endTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="interval" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="recipients" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>